- name: ping them all
  hosts: centos
  tasks:
    - name: pinging
      ping:

- name: install apache
  hosts: centos
  become: true
  become_method: sudo
  tasks:
    - name: Install apache
      yum: 
        name: httpd
        state: present

- name: install nginx
  hosts: ubuntu
  become: true
  become_method: sudo
  tasks:
    - name: install nginx
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started



